nats: 
  addr: "nats://127.0.0.1:4222,nats://127.0.0.1:4223,nats://127.0.0.1:4224"
  user: "user"
  password: "password"
  creat_stream_info:
    - name: "name1"
      live_second: "1h"
      max_len: 1000
    - name: "name2"
      live_second: "1h"
      max_len: 1000