version: "3.7"
services:
  nats1:
    image: nats:latest
    container_name: nats1
    ports:
      - "6222:6222"
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-server1.conf:/etc/nats/nats-server.conf
      - nats1-data:/data
    command: ["-c", "/etc/nats/nats-server.conf", "--js"]
    networks:
      - nats-net

  nats2:
    image: nats:latest
    container_name: nats2
    ports:
      - "6223:6222"
      - "4223:4222"
      - "8223:8222"
    volumes:
      - ./nats-server2.conf:/etc/nats/nats-server.conf
      - nats2-data:/data
    command: ["-c", "/etc/nats/nats-server.conf", "--js"]
    networks:
      - nats-net

  nats3:
    image: nats:latest
    container_name: nats3
    ports:
      - "6224:6222"
      - "4224:4222"
      - "8224:8222"
    volumes:
      - ./nats-server3.conf:/etc/nats/nats-server.conf
      - nats3-data:/data
    command: ["-c", "/etc/nats/nats-server.conf", "--js"]
    networks:
      - nats-net

volumes:
  nats1-data:
  nats2-data:
  nats3-data:

networks:
  nats-net:
    external: true
