master: 
  addr: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&readPreference=primary"
  # addr: "mongodb://127.0.0.1:27019/?replicaSet=rs0&directConnection=true"
  # addr: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&readPreference=primary"
  data_base: "test"
  user_name: ""
  pass_word: ""
second: 
  addr: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&readPreference=secondaryPreferred"
  # addr: "mongodb://127.0.0.1:27017/?replicaSet=rs0&directConnection=true"
  # addr: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&readPreference=secondaryPreferred"
  data_base: "test"
  user_name: ""
  pass_word: ""