// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: common_grpc.proto

package commongrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tracer string `protobuf:"bytes,1,opt,name=Tracer,proto3" json:"Tracer,omitempty"`
}

func (x *LogData) Reset() {
	*x = LogData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogData) ProtoMessage() {}

func (x *LogData) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogData.ProtoReflect.Descriptor instead.
func (*LogData) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *LogData) GetTracer() string {
	if x != nil {
		return x.Tracer
	}
	return ""
}

type UnaryRPCReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogData   *LogData `protobuf:"bytes,1,opt,name=LogData,proto3" json:"LogData,omitempty"`
	EventCode int32    `protobuf:"varint,2,opt,name=EventCode,proto3" json:"EventCode,omitempty"`
	Data      []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UnaryRPCReq) Reset() {
	*x = UnaryRPCReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryRPCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRPCReq) ProtoMessage() {}

func (x *UnaryRPCReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRPCReq.ProtoReflect.Descriptor instead.
func (*UnaryRPCReq) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryRPCReq) GetLogData() *LogData {
	if x != nil {
		return x.LogData
	}
	return nil
}

func (x *UnaryRPCReq) GetEventCode() int32 {
	if x != nil {
		return x.EventCode
	}
	return 0
}

func (x *UnaryRPCReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UnaryRPCRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventCode int32  `protobuf:"varint,1,opt,name=EventCode,proto3" json:"EventCode,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	ErrorCode int32  `protobuf:"varint,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Message   string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *UnaryRPCRes) Reset() {
	*x = UnaryRPCRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryRPCRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRPCRes) ProtoMessage() {}

func (x *UnaryRPCRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRPCRes.ProtoReflect.Descriptor instead.
func (*UnaryRPCRes) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *UnaryRPCRes) GetEventCode() int32 {
	if x != nil {
		return x.EventCode
	}
	return 0
}

func (x *UnaryRPCRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UnaryRPCRes) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *UnaryRPCRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_grpc_proto protoreflect.FileDescriptor

var file_common_grpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x22,
	0x21, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x72, 0x22, 0x6e, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x71, 0x12, 0x2d, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x77, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4c, 0x0a, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x12, 0x3e, 0x0a, 0x08, 0x55, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x50, 0x43, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_common_grpc_proto_rawDescOnce sync.Once
	file_common_grpc_proto_rawDescData = file_common_grpc_proto_rawDesc
)

func file_common_grpc_proto_rawDescGZIP() []byte {
	file_common_grpc_proto_rawDescOnce.Do(func() {
		file_common_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_grpc_proto_rawDescData)
	})
	return file_common_grpc_proto_rawDescData
}

var file_common_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_grpc_proto_goTypes = []any{
	(*LogData)(nil),     // 0: commongrpc.LogData
	(*UnaryRPCReq)(nil), // 1: commongrpc.UnaryRPCReq
	(*UnaryRPCRes)(nil), // 2: commongrpc.UnaryRPCRes
}
var file_common_grpc_proto_depIdxs = []int32{
	0, // 0: commongrpc.UnaryRPCReq.LogData:type_name -> commongrpc.LogData
	1, // 1: commongrpc.Commongrpc.UnaryRPC:input_type -> commongrpc.UnaryRPCReq
	2, // 2: commongrpc.Commongrpc.UnaryRPC:output_type -> commongrpc.UnaryRPCRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_grpc_proto_init() }
func file_common_grpc_proto_init() {
	if File_common_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LogData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UnaryRPCReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UnaryRPCRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_grpc_proto_goTypes,
		DependencyIndexes: file_common_grpc_proto_depIdxs,
		MessageInfos:      file_common_grpc_proto_msgTypes,
	}.Build()
	File_common_grpc_proto = out.File
	file_common_grpc_proto_rawDesc = nil
	file_common_grpc_proto_goTypes = nil
	file_common_grpc_proto_depIdxs = nil
}
