// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: common_grpc.proto

package commongrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Commongrpc_UnaryRPC_FullMethodName = "/commongrpc.Commongrpc/UnaryRPC"
)

// CommongrpcClient is the client API for Commongrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommongrpcClient interface {
	UnaryRPC(ctx context.Context, in *UnaryRPCReq, opts ...grpc.CallOption) (*UnaryRPCRes, error)
}

type commongrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewCommongrpcClient(cc grpc.ClientConnInterface) CommongrpcClient {
	return &commongrpcClient{cc}
}

func (c *commongrpcClient) UnaryRPC(ctx context.Context, in *UnaryRPCReq, opts ...grpc.CallOption) (*UnaryRPCRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnaryRPCRes)
	err := c.cc.Invoke(ctx, Commongrpc_UnaryRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommongrpcServer is the server API for Commongrpc service.
// All implementations should embed UnimplementedCommongrpcServer
// for forward compatibility.
type CommongrpcServer interface {
	UnaryRPC(context.Context, *UnaryRPCReq) (*UnaryRPCRes, error)
}

// UnimplementedCommongrpcServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommongrpcServer struct{}

func (UnimplementedCommongrpcServer) UnaryRPC(context.Context, *UnaryRPCReq) (*UnaryRPCRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryRPC not implemented")
}
func (UnimplementedCommongrpcServer) testEmbeddedByValue() {}

// UnsafeCommongrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommongrpcServer will
// result in compilation errors.
type UnsafeCommongrpcServer interface {
	mustEmbedUnimplementedCommongrpcServer()
}

func RegisterCommongrpcServer(s grpc.ServiceRegistrar, srv CommongrpcServer) {
	// If the following call pancis, it indicates UnimplementedCommongrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Commongrpc_ServiceDesc, srv)
}

func _Commongrpc_UnaryRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRPCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommongrpcServer).UnaryRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Commongrpc_UnaryRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommongrpcServer).UnaryRPC(ctx, req.(*UnaryRPCReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Commongrpc_ServiceDesc is the grpc.ServiceDesc for Commongrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Commongrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commongrpc.Commongrpc",
	HandlerType: (*CommongrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryRPC",
			Handler:    _Commongrpc_UnaryRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common_grpc.proto",
}
