// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: common_grpc.proto

package commongrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Commongrpc_UnaryRPC_FullMethodName = "/commongrpc.Commongrpc/UnaryRPC"
)

// CommongrpcClient is the client API for Commongrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommongrpcClient interface {
	UnaryRPC(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnaryRPCReq, UnaryRPCRes], error)
}

type commongrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewCommongrpcClient(cc grpc.ClientConnInterface) CommongrpcClient {
	return &commongrpcClient{cc}
}

func (c *commongrpcClient) UnaryRPC(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnaryRPCReq, UnaryRPCRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Commongrpc_ServiceDesc.Streams[0], Commongrpc_UnaryRPC_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnaryRPCReq, UnaryRPCRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Commongrpc_UnaryRPCClient = grpc.BidiStreamingClient[UnaryRPCReq, UnaryRPCRes]

// CommongrpcServer is the server API for Commongrpc service.
// All implementations should embed UnimplementedCommongrpcServer
// for forward compatibility.
type CommongrpcServer interface {
	UnaryRPC(grpc.BidiStreamingServer[UnaryRPCReq, UnaryRPCRes]) error
}

// UnimplementedCommongrpcServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommongrpcServer struct{}

func (UnimplementedCommongrpcServer) UnaryRPC(grpc.BidiStreamingServer[UnaryRPCReq, UnaryRPCRes]) error {
	return status.Errorf(codes.Unimplemented, "method UnaryRPC not implemented")
}
func (UnimplementedCommongrpcServer) testEmbeddedByValue() {}

// UnsafeCommongrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommongrpcServer will
// result in compilation errors.
type UnsafeCommongrpcServer interface {
	mustEmbedUnimplementedCommongrpcServer()
}

func RegisterCommongrpcServer(s grpc.ServiceRegistrar, srv CommongrpcServer) {
	// If the following call pancis, it indicates UnimplementedCommongrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Commongrpc_ServiceDesc, srv)
}

func _Commongrpc_UnaryRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommongrpcServer).UnaryRPC(&grpc.GenericServerStream[UnaryRPCReq, UnaryRPCRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Commongrpc_UnaryRPCServer = grpc.BidiStreamingServer[UnaryRPCReq, UnaryRPCRes]

// Commongrpc_ServiceDesc is the grpc.ServiceDesc for Commongrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Commongrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commongrpc.Commongrpc",
	HandlerType: (*CommongrpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UnaryRPC",
			Handler:       _Commongrpc_UnaryRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "common_grpc.proto",
}
