// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: common_grpc.proto

package commongrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryRPCReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UnaryRPCReq_GetTableReq
	//	*UnaryRPCReq_UpdateTableGameReq
	Data isUnaryRPCReq_Data `protobuf_oneof:"Data"`
}

func (x *UnaryRPCReq) Reset() {
	*x = UnaryRPCReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryRPCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRPCReq) ProtoMessage() {}

func (x *UnaryRPCReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRPCReq.ProtoReflect.Descriptor instead.
func (*UnaryRPCReq) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{0}
}

func (m *UnaryRPCReq) GetData() isUnaryRPCReq_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UnaryRPCReq) GetGetTableReq() *GetTableReq {
	if x, ok := x.GetData().(*UnaryRPCReq_GetTableReq); ok {
		return x.GetTableReq
	}
	return nil
}

func (x *UnaryRPCReq) GetUpdateTableGameReq() *UpdateTableGameReq {
	if x, ok := x.GetData().(*UnaryRPCReq_UpdateTableGameReq); ok {
		return x.UpdateTableGameReq
	}
	return nil
}

type isUnaryRPCReq_Data interface {
	isUnaryRPCReq_Data()
}

type UnaryRPCReq_GetTableReq struct {
	GetTableReq *GetTableReq `protobuf:"bytes,1,opt,name=GetTableReq,proto3,oneof"`
}

type UnaryRPCReq_UpdateTableGameReq struct {
	UpdateTableGameReq *UpdateTableGameReq `protobuf:"bytes,2,opt,name=UpdateTableGameReq,proto3,oneof"`
}

func (*UnaryRPCReq_GetTableReq) isUnaryRPCReq_Data() {}

func (*UnaryRPCReq_UpdateTableGameReq) isUnaryRPCReq_Data() {}

type UnaryRPCRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32  `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	// Types that are assignable to Data:
	//
	//	*UnaryRPCRes_GetTableRes
	//	*UnaryRPCRes_UpdateTableGameRes
	//	*UnaryRPCRes_UpdateTableStatusRes
	Data isUnaryRPCRes_Data `protobuf_oneof:"Data"`
}

func (x *UnaryRPCRes) Reset() {
	*x = UnaryRPCRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryRPCRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRPCRes) ProtoMessage() {}

func (x *UnaryRPCRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRPCRes.ProtoReflect.Descriptor instead.
func (*UnaryRPCRes) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryRPCRes) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *UnaryRPCRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (m *UnaryRPCRes) GetData() isUnaryRPCRes_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UnaryRPCRes) GetGetTableRes() *GetTableRes {
	if x, ok := x.GetData().(*UnaryRPCRes_GetTableRes); ok {
		return x.GetTableRes
	}
	return nil
}

func (x *UnaryRPCRes) GetUpdateTableGameRes() *UpdateTableGameRes {
	if x, ok := x.GetData().(*UnaryRPCRes_UpdateTableGameRes); ok {
		return x.UpdateTableGameRes
	}
	return nil
}

func (x *UnaryRPCRes) GetUpdateTableStatusRes() *UpdateTableStatusRes {
	if x, ok := x.GetData().(*UnaryRPCRes_UpdateTableStatusRes); ok {
		return x.UpdateTableStatusRes
	}
	return nil
}

type isUnaryRPCRes_Data interface {
	isUnaryRPCRes_Data()
}

type UnaryRPCRes_GetTableRes struct {
	GetTableRes *GetTableRes `protobuf:"bytes,3,opt,name=GetTableRes,proto3,oneof"`
}

type UnaryRPCRes_UpdateTableGameRes struct {
	UpdateTableGameRes *UpdateTableGameRes `protobuf:"bytes,4,opt,name=UpdateTableGameRes,proto3,oneof"`
}

type UnaryRPCRes_UpdateTableStatusRes struct {
	UpdateTableStatusRes *UpdateTableStatusRes `protobuf:"bytes,5,opt,name=UpdateTableStatusRes,proto3,oneof"`
}

func (*UnaryRPCRes_GetTableRes) isUnaryRPCRes_Data() {}

func (*UnaryRPCRes_UpdateTableGameRes) isUnaryRPCRes_Data() {}

func (*UnaryRPCRes_UpdateTableStatusRes) isUnaryRPCRes_Data() {}

type GetTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  uint64  `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Limit  uint64  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	ClubID uint64  `protobuf:"varint,3,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	GameID int64   `protobuf:"varint,4,opt,name=GameID,proto3" json:"GameID,omitempty"`
	Status []int32 `protobuf:"varint,5,rep,packed,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GetTableReq) Reset() {
	*x = GetTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableReq) ProtoMessage() {}

func (x *GetTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableReq.ProtoReflect.Descriptor instead.
func (*GetTableReq) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetTableReq) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetTableReq) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTableReq) GetClubID() uint64 {
	if x != nil {
		return x.ClubID
	}
	return 0
}

func (x *GetTableReq) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *GetTableReq) GetStatus() []int32 {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetTableRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTableRes) Reset() {
	*x = GetTableRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableRes) ProtoMessage() {}

func (x *GetTableRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableRes.ProtoReflect.Descriptor instead.
func (*GetTableRes) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{3}
}

type UpdateTableGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId    int64  `protobuf:"varint,1,opt,name=TableId,proto3" json:"TableId,omitempty"`
	GameConfig []byte `protobuf:"bytes,2,opt,name=GameConfig,proto3" json:"GameConfig,omitempty"`
}

func (x *UpdateTableGameReq) Reset() {
	*x = UpdateTableGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTableGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableGameReq) ProtoMessage() {}

func (x *UpdateTableGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableGameReq.ProtoReflect.Descriptor instead.
func (*UpdateTableGameReq) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTableGameReq) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *UpdateTableGameReq) GetGameConfig() []byte {
	if x != nil {
		return x.GameConfig
	}
	return nil
}

type UpdateTableGameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTableGameRes) Reset() {
	*x = UpdateTableGameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTableGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableGameRes) ProtoMessage() {}

func (x *UpdateTableGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableGameRes.ProtoReflect.Descriptor instead.
func (*UpdateTableGameRes) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{5}
}

type UpdateTableStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId    int64  `protobuf:"varint,1,opt,name=TableId,proto3" json:"TableId,omitempty"`
	GameConfig []byte `protobuf:"bytes,2,opt,name=GameConfig,proto3" json:"GameConfig,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UpdateTableStatusReq) Reset() {
	*x = UpdateTableStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTableStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableStatusReq) ProtoMessage() {}

func (x *UpdateTableStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateTableStatusReq) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTableStatusReq) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *UpdateTableStatusReq) GetGameConfig() []byte {
	if x != nil {
		return x.GameConfig
	}
	return nil
}

func (x *UpdateTableStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateTableStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTableStatusRes) Reset() {
	*x = UpdateTableStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTableStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableStatusRes) ProtoMessage() {}

func (x *UpdateTableStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableStatusRes.ProtoReflect.Descriptor instead.
func (*UpdateTableStatusRes) Descriptor() ([]byte, []int) {
	return file_common_grpc_proto_rawDescGZIP(), []int{7}
}

var File_common_grpc_proto protoreflect.FileDescriptor

var file_common_grpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x22,
	0xa4, 0x01, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x12,
	0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x50, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x42, 0x06,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xb4, 0x02, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x56, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x81, 0x01,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x75,
	0x62, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x43, 0x6c, 0x75, 0x62, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x4e, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x47, 0x61,
	0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x32, 0x50, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x12, 0x42, 0x0a, 0x08, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x50, 0x43, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x50,
	0x43, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_common_grpc_proto_rawDescOnce sync.Once
	file_common_grpc_proto_rawDescData = file_common_grpc_proto_rawDesc
)

func file_common_grpc_proto_rawDescGZIP() []byte {
	file_common_grpc_proto_rawDescOnce.Do(func() {
		file_common_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_grpc_proto_rawDescData)
	})
	return file_common_grpc_proto_rawDescData
}

var file_common_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_grpc_proto_goTypes = []any{
	(*UnaryRPCReq)(nil),          // 0: commongrpc.UnaryRPCReq
	(*UnaryRPCRes)(nil),          // 1: commongrpc.UnaryRPCRes
	(*GetTableReq)(nil),          // 2: commongrpc.GetTableReq
	(*GetTableRes)(nil),          // 3: commongrpc.GetTableRes
	(*UpdateTableGameReq)(nil),   // 4: commongrpc.UpdateTableGameReq
	(*UpdateTableGameRes)(nil),   // 5: commongrpc.UpdateTableGameRes
	(*UpdateTableStatusReq)(nil), // 6: commongrpc.UpdateTableStatusReq
	(*UpdateTableStatusRes)(nil), // 7: commongrpc.UpdateTableStatusRes
}
var file_common_grpc_proto_depIdxs = []int32{
	2, // 0: commongrpc.UnaryRPCReq.GetTableReq:type_name -> commongrpc.GetTableReq
	4, // 1: commongrpc.UnaryRPCReq.UpdateTableGameReq:type_name -> commongrpc.UpdateTableGameReq
	3, // 2: commongrpc.UnaryRPCRes.GetTableRes:type_name -> commongrpc.GetTableRes
	5, // 3: commongrpc.UnaryRPCRes.UpdateTableGameRes:type_name -> commongrpc.UpdateTableGameRes
	7, // 4: commongrpc.UnaryRPCRes.UpdateTableStatusRes:type_name -> commongrpc.UpdateTableStatusRes
	0, // 5: commongrpc.Commongrpc.UnaryRPC:input_type -> commongrpc.UnaryRPCReq
	1, // 6: commongrpc.Commongrpc.UnaryRPC:output_type -> commongrpc.UnaryRPCRes
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_grpc_proto_init() }
func file_common_grpc_proto_init() {
	if File_common_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UnaryRPCReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UnaryRPCRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetTableRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTableGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTableGameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTableStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_grpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTableStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_grpc_proto_msgTypes[0].OneofWrappers = []any{
		(*UnaryRPCReq_GetTableReq)(nil),
		(*UnaryRPCReq_UpdateTableGameReq)(nil),
	}
	file_common_grpc_proto_msgTypes[1].OneofWrappers = []any{
		(*UnaryRPCRes_GetTableRes)(nil),
		(*UnaryRPCRes_UpdateTableGameRes)(nil),
		(*UnaryRPCRes_UpdateTableStatusRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_grpc_proto_goTypes,
		DependencyIndexes: file_common_grpc_proto_depIdxs,
		MessageInfos:      file_common_grpc_proto_msgTypes,
	}.Build()
	File_common_grpc_proto = out.File
	file_common_grpc_proto_rawDesc = nil
	file_common_grpc_proto_goTypes = nil
	file_common_grpc_proto_depIdxs = nil
}
